/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.CustomerDao;
import dao.CustomerDaoImpl;
import java.util.List;
import javax.swing.JOptionPane;
import model.Customer;
import util.UITheme;

/**
 * Modern Customer Management interface with professional styling.
 * 
 * @author cyita
 */
public class CustomerManagement extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = 
        java.util.logging.Logger.getLogger(CustomerManagement.class.getName());

    /**
     * Creates new form CustomerManagement
     */
    public CustomerManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        displayBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        customerId = new javax.swing.JLabel();
        customerIdTxt = new javax.swing.JTextField();
        firstName = new javax.swing.JLabel();
        firstNameTxt = new javax.swing.JTextField();
        lastName = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        lastNameTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        searchTxt = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Management");
        setLocationRelativeTo(null);
        setBackground(UITheme.BACKGROUND_LIGHT);

        jPanel1.setBackground(UITheme.BACKGROUND_LIGHT);

        displayBtn.setBackground(UITheme.BUTTON_PRIMARY);
        displayBtn.setFont(UITheme.FONT_BUTTON);
        displayBtn.setForeground(UITheme.TEXT_WHITE);
        displayBtn.setText("Display All");
        displayBtn.setBorder(UITheme.createButtonBorder(UITheme.BUTTON_PRIMARY));
        displayBtn.setFocusPainted(false);
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(UITheme.createCardBorder());

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Email", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        customerTable.setFont(UITheme.FONT_BODY);
        customerTable.setGridColor(UITheme.BORDER_LIGHT);
        customerTable.setRowHeight(35);
        customerTable.setSelectionBackground(UITheme.PRIMARY_LIGHT);
        customerTable.setSelectionForeground(UITheme.TEXT_PRIMARY);
        customerTable.setBackground(UITheme.SURFACE);
        customerTable.setForeground(UITheme.TEXT_PRIMARY);
        customerTable.setShowGrid(true);
        jScrollPane2.setViewportView(customerTable);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/engine4.jpg"))); // NOI18N

        jLabel2.setFont(UITheme.FONT_HEADING);
        jLabel2.setForeground(UITheme.TEXT_PRIMARY);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Customer Management");

        jPanel2.setBackground(UITheme.SURFACE);
        jPanel2.setBorder(UITheme.createCardBorder());

        customerId.setFont(UITheme.FONT_BODY_BOLD);
        customerId.setForeground(UITheme.TEXT_PRIMARY);
        customerId.setText("Customer ID");

        customerIdTxt.setBorder(UITheme.createInputBorder());
        customerIdTxt.setFont(UITheme.FONT_BODY);
        customerIdTxt.setBackground(UITheme.SURFACE);
        customerIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdTxtActionPerformed(evt);
            }
        });

        firstName.setFont(UITheme.FONT_BODY_BOLD);
        firstName.setForeground(UITheme.TEXT_PRIMARY);
        firstName.setText("First Name");

        firstNameTxt.setBorder(UITheme.createInputBorder());
        firstNameTxt.setFont(UITheme.FONT_BODY);
        firstNameTxt.setBackground(UITheme.SURFACE);

        lastName.setFont(UITheme.FONT_BODY_BOLD);
        lastName.setForeground(UITheme.TEXT_PRIMARY);
        lastName.setText("Last Name");

        phoneTxt.setBorder(UITheme.createInputBorder());
        phoneTxt.setFont(UITheme.FONT_BODY);
        phoneTxt.setBackground(UITheme.SURFACE);

        email.setFont(UITheme.FONT_BODY_BOLD);
        email.setForeground(UITheme.TEXT_PRIMARY);
        email.setText("Email");

        lastNameTxt.setBorder(UITheme.createInputBorder());
        lastNameTxt.setFont(UITheme.FONT_BODY);
        lastNameTxt.setBackground(UITheme.SURFACE);

        emailTxt.setBorder(UITheme.createInputBorder());
        emailTxt.setFont(UITheme.FONT_BODY);
        emailTxt.setBackground(UITheme.SURFACE);

        searchTxt.setBorder(UITheme.createInputBorder());
        searchTxt.setFont(UITheme.FONT_BODY);
        searchTxt.setBackground(UITheme.SURFACE);

        phone.setFont(UITheme.FONT_BODY_BOLD);
        phone.setForeground(UITheme.TEXT_PRIMARY);
        phone.setText("Phone");

        searchBtn.setBackground(UITheme.BUTTON_INFO);
        searchBtn.setFont(UITheme.FONT_BUTTON);
        searchBtn.setForeground(UITheme.TEXT_WHITE);
        searchBtn.setText("Search By ID");
        searchBtn.setBorder(UITheme.createButtonBorder(UITheme.BUTTON_INFO));
        searchBtn.setFocusPainted(false);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        saveBtn.setBackground(UITheme.BUTTON_SECONDARY);
        saveBtn.setFont(UITheme.FONT_BUTTON);
        saveBtn.setForeground(UITheme.TEXT_WHITE);
        saveBtn.setText("Save");
        saveBtn.setBorder(UITheme.createButtonBorder(UITheme.BUTTON_SECONDARY));
        saveBtn.setFocusPainted(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(UITheme.BUTTON_WARNING);
        updateBtn.setFont(UITheme.FONT_BUTTON);
        updateBtn.setForeground(UITheme.TEXT_WHITE);
        updateBtn.setText("Update");
        updateBtn.setBorder(UITheme.createButtonBorder(UITheme.BUTTON_WARNING));
        updateBtn.setFocusPainted(false);
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(UITheme.BUTTON_DANGER);
        deleteBtn.setFont(UITheme.FONT_BUTTON);
        deleteBtn.setForeground(UITheme.TEXT_WHITE);
        deleteBtn.setText("Delete");
        deleteBtn.setBorder(UITheme.createButtonBorder(UITheme.BUTTON_DANGER));
        deleteBtn.setFocusPainted(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customerId)
                                    .addComponent(customerIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstName)
                                    .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(email)
                            .addComponent(emailTxt))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastName)
                            .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone)
                            .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(searchBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerId)
                    .addComponent(firstName)
                    .addComponent(lastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(email))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(phone)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBtn)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(UITheme.BUTTON_PRIMARY);
        jButton1.setFont(UITheme.FONT_BUTTON);
        jButton1.setForeground(UITheme.TEXT_WHITE);
        jButton1.setText("Home");
        jButton1.setBorder(UITheme.createButtonBorder(UITheme.BUTTON_PRIMARY));
        jButton1.setFocusPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(557, 557, 557)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(displayBtn))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(561, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 536, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        if(customerIdTxt.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Customer ID is required!", "VALIDATION", JOptionPane.ERROR_MESSAGE);
        return;
    }
        
    if(firstNameTxt.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "First Name is required!", "VALIDATION", JOptionPane.ERROR_MESSAGE);
        return;
    }
     if (!firstNameTxt.getText().trim().matches("^[A-Za-z ]+$")) {
    JOptionPane.showMessageDialog(this, "Name must contain only letters and spaces!", "VALIDATION",
        JOptionPane.ERROR_MESSAGE
    );
    return;}
    if(lastNameTxt.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this, "Last Name is required!", "VALIDATION", JOptionPane.ERROR_MESSAGE);
        return;}
     if (!lastNameTxt.getText().trim().matches("^[A-Za-z ]+$")) {
    JOptionPane.showMessageDialog(this, "Name must contain only letters and spaces!", "VALIDATION",
        JOptionPane.ERROR_MESSAGE
    );
    return;
     }
    
     if(emailTxt.getText().trim().isEmpty() || !emailTxt.getText().matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")){
         JOptionPane.showMessageDialog(this, "Valid Email is required!", "VALIDATION", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if(phoneTxt.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Phone is required!", "VALIDATION", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!phoneTxt.getText().matches("\\d+")) {
    JOptionPane.showMessageDialog(this, "Phone must contain only positive numbers!", "VALIDATION", JOptionPane.ERROR_MESSAGE);
    return;
    }
     Customer c = new Customer();
    c.setCustomerId(customerIdTxt.getText().trim());
    c.setCustomerFirstName(firstNameTxt.getText().trim());
    c.setCustomerLastName(lastNameTxt.getText().trim());
    c.setCustomerEmail(emailTxt.getText().trim());
    c.setCustomerPhone(phoneTxt.getText().trim());
    
     CustomerDao dao = new CustomerDaoImpl();
    int rows = dao.create(c);

    if(rows > 0){
        JOptionPane.showMessageDialog(this, "Customer Saved Successfully!");
        clearFields();
        loadCustomersToTable();
    } else {
          JOptionPane.showMessageDialog(this, "Customer NOT saved!", "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String id = searchTxt.getText().trim();

    if(id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Enter Customer ID to search.");
        return;
    }

    CustomerDao dao = new CustomerDaoImpl();
    Customer found = dao.searchById(id);

    if(found == null){
        JOptionPane.showMessageDialog(this, "Customer NOT found!");
        clearFields();
        return;
    }

    // Load into fields
    loadCustomerToForm(found);
    customerIdTxt.setEditable(false);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if(customerIdTxt.isEditable()){
        JOptionPane.showMessageDialog(this, "Search for the customer first before updating.");
        return;
    }

    Customer c = buildCustomerFromForm();
    CustomerDao dao = new CustomerDaoImpl();

    int rows = dao.update(c);

    if(rows > 0){
        JOptionPane.showMessageDialog(this, "Customer updated successfully!");
        customerIdTxt.setEditable(true);
        setFieldsEditable(rootPaneCheckingEnabled);
        clearFields();
        loadCustomersToTable();
    } else {
        JOptionPane.showMessageDialog(this, "Update failed!", "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
         if(customerIdTxt.isEditable()){
        JOptionPane.showMessageDialog(this, "Search for a customer first!");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this customer?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);

    if(confirm != JOptionPane.YES_OPTION) return;

    String id = customerIdTxt.getText().trim();
    CustomerDao dao = new CustomerDaoImpl();
    int rows = dao.delete(id);

    if(rows > 0){
        JOptionPane.showMessageDialog(this, "Customer deleted successfully!");
        customerIdTxt.setEditable(true);
        clearFields();
        loadCustomersToTable();
    } else {
        JOptionPane.showMessageDialog(this, "Delete failed!", "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        loadCustomersToTable();
    }//GEN-LAST:event_displayBtnActionPerformed

    private void customerIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIdTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerManagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerId;
    private javax.swing.JTextField customerIdTxt;
    private javax.swing.JTable customerTable;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel firstName;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastName;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JLabel phone;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
private void setFieldsEditable(boolean editable) {
    firstNameTxt.setEditable(editable);
    lastNameTxt.setEditable(editable);
    emailTxt.setEditable(editable);
    phoneTxt.setEditable(editable);
}
    private void clearFields(){
    customerIdTxt.setText("");
    firstNameTxt.setText("");
    lastNameTxt.setText("");
    emailTxt.setText("");
    phoneTxt.setText("");

    customerIdTxt.setEditable(true);
}
private void loadCustomerToForm(Customer c){
    customerIdTxt.setText(c.getCustomerId());
    firstNameTxt.setText(c.getCustomerFirstName());
    lastNameTxt.setText(c.getCustomerLastName());
    emailTxt.setText(c.getCustomerEmail());
    phoneTxt.setText(c.getCustomerPhone());
}
private Customer buildCustomerFromForm(){
    Customer c = new Customer();
    c.setCustomerId(customerIdTxt.getText().trim());
    c.setCustomerFirstName(firstNameTxt.getText().trim());
    c.setCustomerLastName(lastNameTxt.getText().trim());
    c.setCustomerEmail(emailTxt.getText().trim());
    c.setCustomerPhone(phoneTxt.getText().trim());
    return c;
}
private void loadCustomersToTable(){
    CustomerDao dao = new CustomerDaoImpl();
    List<Customer> list = dao.displayAllCustomers();

    String[] cols = {"ID", "First Name", "Last Name", "Email", "Phone"};
    Object[][] data = new Object[list.size()][5];

    for(int i = 0; i < list.size(); i++){
        Customer c = list.get(i);
        data[i][0] = c.getCustomerId();
        data[i][1] = c.getCustomerFirstName();
        data[i][2] = c.getCustomerLastName();
        data[i][3] = c.getCustomerEmail();
        data[i][4] = c.getCustomerPhone();
    }

    customerTable.setModel(new javax.swing.table.DefaultTableModel(data, cols));
}


}

