/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import util.UITheme;

/**
 * Modern, professional home page for the Car Spare Parts Management System.
 * 
 * @author cyita
 */
public class HomePage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomePage.class.getName());

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tileCategory = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tileParts = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tileCustomer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tileSales = new javax.swing.JPanel();
        lbltileSales = new javax.swing.JLabel();
        tileSuppliers = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tileExit = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Spare Parts Management System");
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(true);
        setLocationRelativeTo(null);

        jPanel1.setBackground(UITheme.BACKGROUND_LIGHT);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(UITheme.FONT_TITLE);
        jLabel1.setForeground(UITheme.TEXT_PRIMARY);
        jLabel1.setText("Car Spare Parts Management System");
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1200, 50));

        tileCategory.setBackground(UITheme.SECONDARY);
        tileCategory.setAlignmentX(0.0F);
        tileCategory.setAlignmentY(0.0F);
        tileCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tileCategory.setBorder(UITheme.createCardBorder());
        tileCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tileCategoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tileCategoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tileCategoryMouseExited(evt);
            }
        });

        jLabel2.setFont(UITheme.FONT_SUBHEADING);
        jLabel2.setForeground(UITheme.TEXT_WHITE);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Categories");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout tileCategoryLayout = new javax.swing.GroupLayout(tileCategory);
        tileCategory.setLayout(tileCategoryLayout);
        tileCategoryLayout.setHorizontalGroup(
            tileCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tileCategoryLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        tileCategoryLayout.setVerticalGroup(
            tileCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tileCategoryLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        jPanel1.add(tileCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 200, 140));

        tileParts.setBackground(UITheme.PRIMARY);
        tileParts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tileParts.setBorder(UITheme.createCardBorder());
        tileParts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tilePartsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tilePartsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tilePartsMouseExited(evt);
            }
        });

        jLabel3.setFont(UITheme.FONT_SUBHEADING);
        jLabel3.setForeground(UITheme.TEXT_WHITE);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Parts");

        javax.swing.GroupLayout tilePartsLayout = new javax.swing.GroupLayout(tileParts);
        tileParts.setLayout(tilePartsLayout);
        tilePartsLayout.setHorizontalGroup(
            tilePartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tilePartsLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        tilePartsLayout.setVerticalGroup(
            tilePartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tilePartsLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel1.add(tileParts, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 200, 140));

        tileCustomer.setBackground(UITheme.ACCENT_PURPLE);
        tileCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tileCustomer.setBorder(UITheme.createCardBorder());
        tileCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tileCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tileCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tileCustomerMouseExited(evt);
            }
        });

        jLabel4.setFont(UITheme.FONT_SUBHEADING);
        jLabel4.setForeground(UITheme.TEXT_WHITE);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Customers");

        javax.swing.GroupLayout tileCustomerLayout = new javax.swing.GroupLayout(tileCustomer);
        tileCustomer.setLayout(tileCustomerLayout);
        tileCustomerLayout.setHorizontalGroup(
            tileCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tileCustomerLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(29, 29, 29))
        );
        tileCustomerLayout.setVerticalGroup(
            tileCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tileCustomerLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel1.add(tileCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 200, 140));

        tileSales.setBackground(UITheme.ACCENT_ORANGE);
        tileSales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tileSales.setBorder(UITheme.createCardBorder());
        tileSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tileSalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tileSalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tileSalesMouseExited(evt);
            }
        });

        lbltileSales.setFont(UITheme.FONT_SUBHEADING);
        lbltileSales.setForeground(UITheme.TEXT_WHITE);
        lbltileSales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltileSales.setText("Sales");

        javax.swing.GroupLayout tileSalesLayout = new javax.swing.GroupLayout(tileSales);
        tileSales.setLayout(tileSalesLayout);
        tileSalesLayout.setHorizontalGroup(
            tileSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tileSalesLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lbltileSales)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        tileSalesLayout.setVerticalGroup(
            tileSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tileSalesLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbltileSales)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel1.add(tileSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 200, 140));

        tileSuppliers.setBackground(UITheme.ACCENT_PINK);
        tileSuppliers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tileSuppliers.setBorder(UITheme.createCardBorder());
        tileSuppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tileSuppliersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tileSuppliersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tileSuppliersMouseExited(evt);
            }
        });

        jLabel6.setFont(UITheme.FONT_SUBHEADING);
        jLabel6.setForeground(UITheme.TEXT_WHITE);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Suppliers");

        javax.swing.GroupLayout tileSuppliersLayout = new javax.swing.GroupLayout(tileSuppliers);
        tileSuppliers.setLayout(tileSuppliersLayout);
        tileSuppliersLayout.setHorizontalGroup(
            tileSuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tileSuppliersLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        tileSuppliersLayout.setVerticalGroup(
            tileSuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tileSuppliersLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(41, 41, 41))
        );

        jPanel1.add(tileSuppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 200, 140));

        tileExit.setBackground(UITheme.ERROR);
        tileExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tileExit.setBorder(UITheme.createCardBorder());
        tileExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tileExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tileExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tileExitMouseExited(evt);
            }
        });

        jLabel7.setFont(UITheme.FONT_SUBHEADING);
        jLabel7.setForeground(UITheme.TEXT_WHITE);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Exit System");

        javax.swing.GroupLayout tileExitLayout = new javax.swing.GroupLayout(tileExit);
        tileExit.setLayout(tileExitLayout);
        tileExitLayout.setHorizontalGroup(
            tileExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tileExitLayout.setVerticalGroup(
            tileExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tileExitLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel7)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel1.add(tileExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, 200, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tileCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tileCategoryMouseClicked
        // TODO add your handling code here:
        new CategoryManagement().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tileCategoryMouseClicked

    private void tilePartsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tilePartsMouseClicked
        // TODO add your handling code here:
        new PartManagement().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tilePartsMouseClicked

    private void tileCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tileCustomerMouseClicked
        // TODO add your handling code here:
        new CustomerManagement().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_tileCustomerMouseClicked

    private void tileSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tileSalesMouseClicked
        // TODO add your handling code here:
        new SalesManagement().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_tileSalesMouseClicked

    private void tileSuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tileSuppliersMouseClicked
        // TODO add your handling code here:
        new SupplierManagement().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tileSuppliersMouseClicked

    private void tileExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tileExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tileExitMouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel2MouseEntered

    private void tileCategoryMouseEntered(java.awt.event.MouseEvent evt) {
        tileCategory.setBackground(UITheme.SECONDARY_LIGHT);
        tileCategory.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(UITheme.TEXT_WHITE, 3, true),
            new javax.swing.border.EmptyBorder(16, 16, 16, 16)
        ));
    }

    private void tileCategoryMouseExited(java.awt.event.MouseEvent evt) {
        tileCategory.setBackground(UITheme.SECONDARY);
        tileCategory.setBorder(UITheme.createCardBorder());
    }

    private void tilePartsMouseEntered(java.awt.event.MouseEvent evt) {
        tileParts.setBackground(UITheme.PRIMARY_LIGHT);
        tileParts.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(UITheme.TEXT_WHITE, 3, true),
            new javax.swing.border.EmptyBorder(16, 16, 16, 16)
        ));
    }

    private void tilePartsMouseExited(java.awt.event.MouseEvent evt) {
        tileParts.setBackground(UITheme.PRIMARY);
        tileParts.setBorder(UITheme.createCardBorder());
    }

    private void tileCustomerMouseEntered(java.awt.event.MouseEvent evt) {
        tileCustomer.setBackground(new java.awt.Color(
            Math.min(255, UITheme.ACCENT_PURPLE.getRed() + 20),
            Math.min(255, UITheme.ACCENT_PURPLE.getGreen() + 20),
            Math.min(255, UITheme.ACCENT_PURPLE.getBlue() + 20)
        ));
        tileCustomer.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(UITheme.TEXT_WHITE, 3, true),
            new javax.swing.border.EmptyBorder(16, 16, 16, 16)
        ));
    }

    private void tileCustomerMouseExited(java.awt.event.MouseEvent evt) {
        tileCustomer.setBackground(UITheme.ACCENT_PURPLE);
        tileCustomer.setBorder(UITheme.createCardBorder());
    }

    private void tileSalesMouseEntered(java.awt.event.MouseEvent evt) {
        tileSales.setBackground(new java.awt.Color(
            Math.min(255, UITheme.ACCENT_ORANGE.getRed() + 20),
            Math.min(255, UITheme.ACCENT_ORANGE.getGreen() + 20),
            Math.min(255, UITheme.ACCENT_ORANGE.getBlue() + 20)
        ));
        tileSales.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(UITheme.TEXT_WHITE, 3, true),
            new javax.swing.border.EmptyBorder(16, 16, 16, 16)
        ));
    }

    private void tileSalesMouseExited(java.awt.event.MouseEvent evt) {
        tileSales.setBackground(UITheme.ACCENT_ORANGE);
        tileSales.setBorder(UITheme.createCardBorder());
    }

    private void tileSuppliersMouseEntered(java.awt.event.MouseEvent evt) {
        tileSuppliers.setBackground(new java.awt.Color(
            Math.min(255, UITheme.ACCENT_PINK.getRed() + 20),
            Math.min(255, UITheme.ACCENT_PINK.getGreen() + 20),
            Math.min(255, UITheme.ACCENT_PINK.getBlue() + 20)
        ));
        tileSuppliers.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(UITheme.TEXT_WHITE, 3, true),
            new javax.swing.border.EmptyBorder(16, 16, 16, 16)
        ));
    }

    private void tileSuppliersMouseExited(java.awt.event.MouseEvent evt) {
        tileSuppliers.setBackground(UITheme.ACCENT_PINK);
        tileSuppliers.setBorder(UITheme.createCardBorder());
    }

    private void tileExitMouseEntered(java.awt.event.MouseEvent evt) {
        tileExit.setBackground(UITheme.BUTTON_DANGER_HOVER);
        tileExit.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(UITheme.TEXT_WHITE, 3, true),
            new javax.swing.border.EmptyBorder(16, 16, 16, 16)
        ));
    }

    private void tileExitMouseExited(java.awt.event.MouseEvent evt) {
        tileExit.setBackground(UITheme.ERROR);
        tileExit.setBorder(UITheme.createCardBorder());
    }

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new CategoryManagement().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Check if user is logged in, otherwise show login */
        java.awt.EventQueue.invokeLater(() -> {
            if (Login.isLoggedIn()) {
                new HomePage().setVisible(true);
            } else {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbltileSales;
    private javax.swing.JPanel tileCategory;
    private javax.swing.JPanel tileCustomer;
    private javax.swing.JPanel tileExit;
    private javax.swing.JPanel tileParts;
    private javax.swing.JPanel tileSales;
    private javax.swing.JPanel tileSuppliers;
    // End of variables declaration//GEN-END:variables
}
