/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import util.UITheme;

/**
 * Modern Part Management interface with professional styling.
 * 
 * @author cyita
 */
public class PartManagement extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = 
        java.util.logging.Logger.getLogger(PartManagement.class.getName());

    /**
     * Creates new form PartManagement
     */
    public PartManagement() {
        initComponents();
        loadCategoriesToCombo();
        loadSuppliersToCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        partCode = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        partCodeTxt = new javax.swing.JTextField();
        partName = new javax.swing.JLabel();
        partNameTxt = new javax.swing.JTextField();
        brandName = new javax.swing.JLabel();
        brandTxt = new javax.swing.JTextField();
        price = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        stockQty = new javax.swing.JLabel();
        stockQtyTxt = new javax.swing.JTextField();
        categoryComboBox = new javax.swing.JLabel();
        categoryComboTxt = new javax.swing.JComboBox<>();
        supplierComboBox = new javax.swing.JLabel();
        supplierComboTxt = new javax.swing.JComboBox<>();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        partTable = new javax.swing.JScrollPane();
        tablePart = new javax.swing.JTable();
        displayBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Part Management");
        setLocationRelativeTo(null);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setBackground(UITheme.BACKGROUND_LIGHT);

        leftPanel.setBackground(UITheme.SURFACE);
        leftPanel.setBorder(UITheme.createCardBorder());

        partCode.setText("Part Code");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Part Details");

        partCodeTxt.setBorder(UITheme.createInputBorder());
        partCodeTxt.setFont(UITheme.FONT_BODY);
        partCodeTxt.setBackground(UITheme.SURFACE);
        partCodeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partCodeTxtActionPerformed(evt);
            }
        });

        partName.setText("Part Name");

        partNameTxt.setBorder(UITheme.createInputBorder());
        partNameTxt.setFont(UITheme.FONT_BODY);
        partNameTxt.setBackground(UITheme.SURFACE);

        brandName.setText("Brand");

        brandTxt.setBorder(UITheme.createInputBorder());
        brandTxt.setFont(UITheme.FONT_BODY);
        brandTxt.setBackground(UITheme.SURFACE);

        price.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        price.setText("Price");

        priceTxt.setBorder(UITheme.createInputBorder());
        priceTxt.setFont(UITheme.FONT_BODY);
        priceTxt.setBackground(UITheme.SURFACE);

        stockQty.setText("Stock Quantity");

        stockQtyTxt.setBorder(UITheme.createInputBorder());
        stockQtyTxt.setFont(UITheme.FONT_BODY);
        stockQtyTxt.setBackground(UITheme.SURFACE);
        stockQtyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockQtyTxtActionPerformed(evt);
            }
        });

        categoryComboBox.setText("Category");

        categoryComboTxt.setForeground(new java.awt.Color(255, 255, 255));
        categoryComboTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoryComboTxt.setBorder(UITheme.createInputBorder());
        categoryComboTxt.setFont(UITheme.FONT_BODY);
        categoryComboTxt.setBackground(UITheme.SURFACE);
        categoryComboTxt.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                categoryComboTxtAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        categoryComboTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboTxtActionPerformed(evt);
            }
        });

        supplierComboBox.setText("Supplier");

        supplierComboTxt.setBorder(UITheme.createInputBorder());
        supplierComboTxt.setFont(UITheme.FONT_BODY);
        supplierComboTxt.setBackground(UITheme.SURFACE);
        supplierComboTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierComboTxtActionPerformed(evt);
            }
        });

        saveBtn.setBackground(UITheme.BUTTON_SECONDARY);
        saveBtn.setFont(UITheme.FONT_BUTTON);
        saveBtn.setForeground(UITheme.TEXT_WHITE);
        saveBtn.setText("Save");
        saveBtn.setBorder(UITheme.createButtonBorder(UITheme.BUTTON_SECONDARY));
        saveBtn.setFocusPainted(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(UITheme.BUTTON_WARNING);
        updateBtn.setFont(UITheme.FONT_BUTTON);
        updateBtn.setForeground(UITheme.TEXT_WHITE);
        updateBtn.setText("Update");
        updateBtn.setBorder(UITheme.createButtonBorder(UITheme.BUTTON_WARNING));
        updateBtn.setFocusPainted(false);
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(UITheme.BUTTON_DANGER);
        deleteBtn.setFont(UITheme.FONT_BUTTON);
        deleteBtn.setForeground(UITheme.TEXT_WHITE);
        deleteBtn.setText("Delete");
        deleteBtn.setBorder(UITheme.createButtonBorder(UITheme.BUTTON_DANGER));
        deleteBtn.setFocusPainted(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        searchBtn.setBackground(UITheme.BUTTON_INFO);
        searchBtn.setFont(UITheme.FONT_BUTTON);
        searchBtn.setForeground(UITheme.TEXT_WHITE);
        searchBtn.setText("Search by ID");
        searchBtn.setBorder(UITheme.createButtonBorder(UITheme.BUTTON_INFO));
        searchBtn.setFocusPainted(false);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brandTxt)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(partCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn)
                        .addGap(248, 248, 248))
                    .addComponent(categoryComboTxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stockQty)
                            .addComponent(stockQtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(brandName)
                            .addGroup(leftPanelLayout.createSequentialGroup()
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(supplierComboTxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(partNameTxt, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(partCodeTxt)
                        .addContainerGap())
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supplierComboBox)
                            .addComponent(categoryComboBox)
                            .addComponent(partName))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partCode)
                    .addComponent(searchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(partCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(partName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(partNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockQty)
                    .addComponent(price))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockQtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(categoryComboBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryComboTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplierComboBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplierComboTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(updateBtn))
                .addGap(32, 32, 32)
                .addComponent(deleteBtn)
                .addContainerGap())
        );

        jLabel1.setFont(UITheme.FONT_HEADING);
        jLabel1.setForeground(UITheme.TEXT_PRIMARY);
        jLabel1.setText("Parts Management");

        partTable.setBackground(UITheme.SURFACE);
        partTable.setBorder(UITheme.createCardBorder());

        tablePart.setBackground(UITheme.SURFACE);
        tablePart.setFont(UITheme.FONT_BODY);
        tablePart.setGridColor(UITheme.BORDER_LIGHT);
        tablePart.setRowHeight(35);
        tablePart.setSelectionBackground(UITheme.PRIMARY_LIGHT);
        tablePart.setSelectionForeground(UITheme.TEXT_PRIMARY);
        tablePart.setForeground(UITheme.TEXT_PRIMARY);
        tablePart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "part code", "part name", "Brand", "price", "stock quantity", "category", "supplier"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablePart.setGridColor(java.awt.Color.lightGray);
        tablePart.setShowGrid(true);
        tablePart.setShowHorizontalLines(true);
        tablePart.setShowVerticalLines(false);
        partTable.setViewportView(tablePart);

        displayBtn.setBackground(UITheme.BUTTON_PRIMARY);
        displayBtn.setFont(UITheme.FONT_BUTTON);
        displayBtn.setForeground(UITheme.TEXT_WHITE);
        displayBtn.setText("Display All");
        displayBtn.setBorder(UITheme.createButtonBorder(UITheme.BUTTON_PRIMARY));
        displayBtn.setFocusPainted(false);
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(UITheme.FONT_SMALL);
        jLabel3.setForeground(UITheme.TEXT_SECONDARY);
        jLabel3.setText("Manage your inventory parts with ease.");

        jButton1.setBackground(UITheme.BUTTON_PRIMARY);
        jButton1.setFont(UITheme.FONT_BUTTON);
        jButton1.setForeground(UITheme.TEXT_WHITE);
        jButton1.setText("Home");
        jButton1.setBorder(UITheme.createButtonBorder(UITheme.BUTTON_PRIMARY));
        jButton1.setFocusPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(displayBtn)
                                .addContainerGap(488, Short.MAX_VALUE))
                            .addComponent(partTable)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(displayBtn)
                        .addGap(18, 18, 18)
                        .addComponent(partTable, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        loadPartsToTable();
    }//GEN-LAST:event_displayBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed

        // TODO add your handling code here:
        String code = partCodeTxt.getText().trim();
        if (code.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter part code to search.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        dao.PartDao dao = new dao.PartDaoImpl();
        model.Part found = dao.searchByCode(code);
        if (found == null) {
            JOptionPane.showMessageDialog(this, "No part found with code " + code, "Not found", JOptionPane.INFORMATION_MESSAGE);
            clearPartFields();
            partCodeTxt.setEditable(true);
            return;
        }
        loadPartToForm(found);
        partCodeTxt.setEditable(false);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        if (partCodeTxt.getText().trim().isEmpty() || partCodeTxt.isEditable()) {
            JOptionPane.showMessageDialog(this, "Search the part first to delete.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete part " + partCodeTxt.getText() + "?", "Confirm Delete", JOptionPane.OK_CANCEL_OPTION);
        if (confirm != JOptionPane.OK_OPTION) return;
        dao.PartDao dao = new dao.PartDaoImpl();
        int rows = dao.delete(partCodeTxt.getText().trim());
        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Part deleted.");
            partCodeTxt.setEditable(true);
            clearPartFields();
            loadPartsToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to delete part.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if (partCodeTxt.getText().trim().isEmpty() || partCodeTxt.isEditable()) {
            JOptionPane.showMessageDialog(this, "Search the part first (code must be locked).", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // re-use validations from save (price & stock)
        double price;
        int stock;
        try {
            price = Double.parseDouble(priceTxt.getText().trim());
            if (price < 0) throw new NumberFormatException();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Price must be a positive number", "Validation", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            stock = Integer.parseInt(stockQtyTxt.getText().trim());
            if (stock < 0) throw new NumberFormatException();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Stock quantity must be a non-negative integer", "Validation", JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        Object catObj = categoryComboTxt.getSelectedItem();
        if (catObj == null) {
            JOptionPane.showMessageDialog(this, "Select a category", "Validation", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String categoryId = (String) ((catObj instanceof model.Category) ? ((model.Category)catObj).getCategoryId() : (String)catObj);
        Object supObj = supplierComboTxt.getSelectedItem();
        String supplierId = null;
        if (supObj != null) supplierId = (String) ((supObj instanceof model.Supplier) ? ((model.Supplier)supObj).getSupplierId() : (String)supObj);

        model.Part p = new model.Part(partCodeTxt.getText().trim(), partNameTxt.getText().trim(), brandTxt.getText().trim(), categoryId, price, stock, supplierId);
        dao.PartDao dao = new dao.PartDaoImpl();
        int rows = dao.update(p);
        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Part updated successfully.");
            partCodeTxt.setEditable(true);
            clearPartFields();
            loadPartsToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update part.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        if(partCodeTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Part Code is required!", "VALIDATION", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(partNameTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Part Name is required!", "VALIDATION", JOptionPane.ERROR_MESSAGE);
            return;
        }
         if (!partNameTxt.getText().trim().matches("^[A-Za-z ]+$")) {
    JOptionPane.showMessageDialog(this, "Name must contain only letters and spaces!", "VALIDATION",
        JOptionPane.ERROR_MESSAGE
    );
    return;}
        if(brandTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Brand is required!", "VALIDATION", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(priceTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Price is required!", "VALIDATION", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (stockQtyTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Stock quantity is required", "Validation", JOptionPane.ERROR_MESSAGE);
            return;
        }
         if (!stockQtyTxt.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Stock Quantity must contain only positive numbers!", "VALIDATION", JOptionPane.ERROR_MESSAGE);
    return;
    }
        double price;
        int stock;
        try {
            price = Double.parseDouble(priceTxt.getText().trim());
            if (price < 0) throw new NumberFormatException("negative");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Price must be a positive number", "Validation", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            stock = Integer.parseInt(stockQtyTxt.getText().trim());
            if (stock < 0) throw new NumberFormatException("negative");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Stock quantity must be a non-negative integer", "Validation", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // category and supplier selection validation
        Object catObj = categoryComboTxt.getSelectedItem();
        if (catObj == null) {
            JOptionPane.showMessageDialog(this, "Select a category", "Validation", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String categoryId = (String) ((catObj instanceof model.Category) ? ((model.Category)catObj).getCategoryId() : (String)catObj);

        Object supObj = supplierComboTxt.getSelectedItem();
        String supplierId = null;
        if (supObj != null) {
            supplierId = (String) ((supObj instanceof model.Supplier) ? ((model.Supplier)supObj).getSupplierId() : (String)supObj);
        }

        // Build Part object
        model.Part p = new model.Part();
        p.setPartCode(partCodeTxt.getText().trim());
        p.setPartName(partNameTxt.getText().trim());
        p.setBrand(brandTxt.getText().trim());
        p.setPrice(price);
        p.setStockQuantity(stock);
        p.setCategoryId(categoryId);
        p.setSupplierId(supplierId);

        // DAO call
        dao.PartDao dao = new dao.PartDaoImpl();
        if (dao.exists(p.getPartCode())) {
            JOptionPane.showMessageDialog(this, "Part code already exists. Use update instead.", "Validation", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int rows = dao.create(p);
        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Part saved successfully.");
            partCodeTxt.setEditable(false); // lock until cleared
            clearPartFields();
            loadPartsToTable(); // refresh table
        } else {
            JOptionPane.showMessageDialog(this, "Failed to save part.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void categoryComboTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryComboTxtActionPerformed

    private void categoryComboTxtAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_categoryComboTxtAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryComboTxtAncestorMoved

    private void stockQtyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockQtyTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockQtyTxtActionPerformed

    private void partCodeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partCodeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partCodeTxtActionPerformed

    private void supplierComboTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierComboTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierComboTxtActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PartManagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brandName;
    private javax.swing.JTextField brandTxt;
    private javax.swing.JLabel categoryComboBox;
    private javax.swing.JComboBox<String> categoryComboTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel partCode;
    private javax.swing.JTextField partCodeTxt;
    private javax.swing.JLabel partName;
    private javax.swing.JTextField partNameTxt;
    private javax.swing.JScrollPane partTable;
    private javax.swing.JLabel price;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel stockQty;
    private javax.swing.JTextField stockQtyTxt;
    private javax.swing.JLabel supplierComboBox;
    private javax.swing.JComboBox<String> supplierComboTxt;
    private javax.swing.JTable tablePart;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
private void clearPartFields() {
    partCodeTxt.setText("");
    partNameTxt.setText("");
    brandTxt.setText("");
    priceTxt.setText("");
    stockQtyTxt.setText("");
    categoryComboTxt.setSelectedIndex(-1);
    supplierComboTxt.setSelectedIndex(-1);
    partCodeTxt.setEditable(true);
}

private void loadPartToForm(model.Part p) {
    if (p == null) return;
    partCodeTxt.setText(p.getPartCode());
    partNameTxt.setText(p.getPartName());
    brandTxt.setText(p.getBrand());
    priceTxt.setText(String.valueOf(p.getPrice()));
    stockQtyTxt.setText(String.valueOf(p.getStockQuantity()));
    // select category and supplier in combo boxes
    selectComboItemById(categoryComboTxt, p.getCategoryId());
    selectComboItemById(supplierComboTxt, p.getSupplierId());
}

private void selectComboItemById(javax.swing.JComboBox combo, String id) {
    for (int i = 0; i < combo.getItemCount(); i++) {
        Object obj = combo.getItemAt(i);

        if (obj instanceof model.Category) {
            model.Category c = (model.Category) obj;
            if (c.getCategoryId().equals(id)) {
                combo.setSelectedIndex(i);
                return;
            }
        }
        else if (obj instanceof model.Supplier) {
            model.Supplier s = (model.Supplier) obj;
            if (s.getSupplierId().equals(id)) {
                combo.setSelectedIndex(i);
                return;
            }
        }
    }
}


private void loadPartsToTable() {
    dao.PartDao dao = new dao.PartDaoImpl();
    java.util.List<model.Part> list = dao.displayAllParts();
    String[] cols = {"Part Code", "Part Name", "Brand", "Category ID", "Price", "Stock", "Supplier ID"};
    Object[][] data = new Object[list.size()][cols.length];
    for (int i = 0; i < list.size(); i++) {
        model.Part p = list.get(i);
        data[i][0] = p.getPartCode();
        data[i][1] = p.getPartName();
        data[i][2] = p.getBrand();
        data[i][3] = p.getCategoryId();
        data[i][4] = p.getPrice();
        data[i][5] = p.getStockQuantity();
        data[i][6] = p.getSupplierId();
    }
    tablePart.setModel(new javax.swing.table.DefaultTableModel(data, cols));
}

private void loadCategoriesToCombo() {
    dao.CategoryDao cdao = new dao.CategoryDaoImpl();
    java.util.List<model.Category> cats = cdao.displayAllCategories();
    categoryComboTxt.removeAllItems();
    for (model.Category c : cats) categoryComboTxt.addItem(c.getCategoryId());
}

private void loadSuppliersToCombo() {
    dao.SupplierDao sdao = new dao.SupplierDaoImpl();
    java.util.List<model.Supplier> sups = sdao.displayAllSuppliers();
    supplierComboTxt.removeAllItems();
    for (model.Supplier s : sups) supplierComboTxt.addItem(s.getSupplierId());
}
}





