/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.SalesDao;
import dao.SalesDaoImpl;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import model.Sales;
import util.UITheme;

/**
 * Modern Sales Management interface with professional styling.
 * 
 * @author cyita
 */
public class SalesManagement extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = 
        java.util.logging.Logger.getLogger(SalesManagement.class.getName());

    /**
     * Creates new form SalesManagement
     */
    public SalesManagement() {
        initComponents();
        loadPartsToCombo();
        loadCustomersToCombo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        salesDate = new javax.swing.JLabel();
        part = new javax.swing.JLabel();
        salesIdTxt = new javax.swing.JTextField();
        salesId = new javax.swing.JLabel();
        partComboTxt = new javax.swing.JComboBox<>();
        customer = new javax.swing.JLabel();
        customerComboTxt = new javax.swing.JComboBox<>();
        quantity = new javax.swing.JLabel();
        salesDateTxt = new javax.swing.JTextField();
        quantityTxt = new javax.swing.JTextField();
        totalPrice = new javax.swing.JLabel();
        totalPriceTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        displayBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Management");
        setLocationRelativeTo(null);

        jPanel1.setBackground(UITheme.BACKGROUND_LIGHT);

        jPanel2.setBackground(UITheme.SURFACE);
        jPanel2.setBorder(UITheme.createCardBorder());

        salesDate.setFont(UITheme.FONT_BODY_BOLD);
        salesDate.setForeground(UITheme.TEXT_PRIMARY);
        salesDate.setText("Sales Date");

        part.setFont(UITheme.FONT_BODY_BOLD);
        part.setForeground(UITheme.TEXT_PRIMARY);
        part.setText("Part");

        salesIdTxt.setBorder(UITheme.createInputBorder());
        salesIdTxt.setFont(UITheme.FONT_BODY);
        salesIdTxt.setBackground(UITheme.SURFACE);

        salesId.setFont(UITheme.FONT_BODY_BOLD);
        salesId.setForeground(UITheme.TEXT_PRIMARY);
        salesId.setText("Sales ID");

        partComboTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        partComboTxt.setBorder(UITheme.createInputBorder());
        partComboTxt.setFont(UITheme.FONT_BODY);
        partComboTxt.setBackground(UITheme.SURFACE);

        customer.setFont(UITheme.FONT_BODY_BOLD);
        customer.setForeground(UITheme.TEXT_PRIMARY);
        customer.setText("Customer");

        customerComboTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        customerComboTxt.setBorder(UITheme.createInputBorder());
        customerComboTxt.setFont(UITheme.FONT_BODY);
        customerComboTxt.setBackground(UITheme.SURFACE);
        customerComboTxt.setOpaque(true);
        customerComboTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerComboTxtActionPerformed(evt);
            }
        });

        quantity.setFont(UITheme.FONT_BODY_BOLD);
        quantity.setForeground(UITheme.TEXT_PRIMARY);
        quantity.setText("Quantity");

        salesDateTxt.setBorder(UITheme.createInputBorder());
        salesDateTxt.setFont(UITheme.FONT_BODY);
        salesDateTxt.setBackground(UITheme.SURFACE);
        salesDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesDateTxtActionPerformed(evt);
            }
        });

        quantityTxt.setBorder(UITheme.createInputBorder());
        quantityTxt.setFont(UITheme.FONT_BODY);
        quantityTxt.setBackground(UITheme.SURFACE);

        totalPrice.setFont(UITheme.FONT_BODY_BOLD);
        totalPrice.setForeground(UITheme.TEXT_PRIMARY);
        totalPrice.setText("Total Price");

        totalPriceTxt.setBorder(UITheme.createInputBorder());
        totalPriceTxt.setFont(UITheme.FONT_BODY);
        totalPriceTxt.setBackground(UITheme.SURFACE);

        searchBtn.setBackground(UITheme.BUTTON_INFO);
        searchBtn.setFont(UITheme.FONT_BUTTON);
        searchBtn.setForeground(UITheme.TEXT_WHITE);
        searchBtn.setText("Search");
        searchBtn.setBorder(UITheme.createButtonBorder(UITheme.BUTTON_INFO));
        searchBtn.setFocusPainted(false);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        savebtn.setBackground(new java.awt.Color(85, 139, 47));
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sales Management");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(salesDate)
                        .addComponent(totalPrice)
                        .addComponent(quantity)
                        .addComponent(salesId)
                        .addComponent(customer)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(savebtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(searchBtn))
                        .addComponent(salesIdTxt)
                        .addComponent(partComboTxt, 0, 406, Short.MAX_VALUE)
                        .addComponent(customerComboTxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quantityTxt)
                        .addComponent(totalPriceTxt)
                        .addComponent(salesDateTxt)
                        .addComponent(part, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(salesId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salesIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(part)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(partComboTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerComboTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quantity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salesDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salesDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(savebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(UITheme.SURFACE);
        jScrollPane1.setBorder(UITheme.createCardBorder());
        jScrollPane1.setPreferredSize(null);

        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sales ID", "PART", "CUSTOMER", "TOTAL PRICE", "DATE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        salesTable.setFont(UITheme.FONT_BODY);
        salesTable.setGridColor(UITheme.BORDER_LIGHT);
        salesTable.setRowHeight(35);
        salesTable.setSelectionBackground(UITheme.PRIMARY_LIGHT);
        salesTable.setSelectionForeground(UITheme.TEXT_PRIMARY);
        salesTable.setBackground(UITheme.SURFACE);
        salesTable.setForeground(UITheme.TEXT_PRIMARY);
        salesTable.setShowGrid(true);
        salesTable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(salesTable);

        displayBtn.setBackground(new java.awt.Color(150, 185, 248));
        displayBtn.setText("Display All");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(37, 99, 235));
        jButton1.setText("Home");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                                .addContainerGap(12, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(displayBtn)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(15, 15, 15)
                        .addComponent(displayBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerComboTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerComboTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerComboTxtActionPerformed

    private void salesDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salesDateTxtActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
         String id = salesIdTxt.getText().trim();
    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter Sales ID first!", "ERROR", JOptionPane.ERROR_MESSAGE);
        return;
    }

    dao.SalesDao dao = new dao.SalesDaoImpl();
    model.Sales s = dao.searchById(id);

    if (s == null) {
        JOptionPane.showMessageDialog(this, "Sale not found!", "INFO", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    partComboTxt.setSelectedItem(s.getPartCode());
    customerComboTxt.setSelectedItem(s.getCustomerId());
    quantityTxt.setText(String.valueOf(s.getQuantity()));
    totalPriceTxt.setText(String.valueOf(s.getTotalPrice()));
    salesDateTxt.setText(String.valueOf(s.getSaleDate()));

    salesIdTxt.setEditable(false);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
            loadSalesToTable();

    }//GEN-LAST:event_displayBtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
         if(salesIdTxt.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Sales ID is required!", "ERROR", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if(partComboTxt.getSelectedItem() == null){
        JOptionPane.showMessageDialog(this, "Select a part!", "ERROR", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if(customerComboTxt.getSelectedItem() == null){
        JOptionPane.showMessageDialog(this, "Select a customer!", "ERROR", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if(quantityTxt.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Quantity is required!", "ERROR", JOptionPane.ERROR_MESSAGE);
        return;
    }
     if (!quantityTxt.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Stocl Quantity must contain only positive numbers!", "Error", JOptionPane.ERROR_MESSAGE);
    return;
    }

    if(totalPriceTxt.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Price is required!", "ERROR", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if(salesDateTxt.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Sale date is required!", "ERROR", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int qty;
    double price;

    try {
        qty = Integer.parseInt(quantityTxt.getText().trim());
        if(qty <= 0){
            JOptionPane.showMessageDialog(this, "Quantity must be positive!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (NumberFormatException ex){
        JOptionPane.showMessageDialog(this, "Quantity must be a number!", "ERROR", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        price = Double.parseDouble(totalPriceTxt.getText().trim());
        if(price <= 0){
            JOptionPane.showMessageDialog(this, "Price must be positive!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (NumberFormatException ex){
        JOptionPane.showMessageDialog(this, "Price must be a number!", "ERROR", JOptionPane.ERROR_MESSAGE);
        return;
    }

    LocalDateTime saleDate;

    try {
        
        DateTimeFormatter fmt1 = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        DateTimeFormatter fmt2 = DateTimeFormatter.ofPattern("yyyy-MM-dd");

        String txt = salesDateTxt.getText().trim();

        if(txt.length() == 10) {
            // yyyy-MM-dd → convert to midnight
            saleDate = LocalDate.parse(txt, fmt2).atStartOfDay();
        } else {
            saleDate = LocalDateTime.parse(txt, fmt1);
        }

    } catch (Exception ex){
        JOptionPane.showMessageDialog(this,
                "Invalid date format!\nUse: yyyy-MM-dd!",
                "DATE ERROR", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // ===== 4. BUILD MODEL =====
    Sales s = new Sales();
    s.setSalesId(salesIdTxt.getText().trim());
    s.setPartCode(partComboTxt.getSelectedItem().toString());
    s.setCustomerId(customerComboTxt.getSelectedItem().toString());
    s.setQuantity(qty);
    s.setTotalPrice(qty * price);
    s.setSaleDate(saleDate);   // Works because field is LocalDateTime

    // ===== 5. SAVE TO DB =====
    SalesDao dao = new SalesDaoImpl();
    int result = dao.create(s);

    if(result > 0){
        JOptionPane.showMessageDialog(this, "Sale recorded successfully!");

        // Clear form
        salesIdTxt.setText("");
        quantityTxt.setText("");
        totalPriceTxt.setText("");
        salesDateTxt.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "Failed to save!", "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_savebtnActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SalesManagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customer;
    private javax.swing.JComboBox<String> customerComboTxt;
    private javax.swing.JButton displayBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel part;
    private javax.swing.JComboBox<String> partComboTxt;
    private javax.swing.JLabel quantity;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JLabel salesDate;
    private javax.swing.JTextField salesDateTxt;
    private javax.swing.JLabel salesId;
    private javax.swing.JTextField salesIdTxt;
    private javax.swing.JTable salesTable;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel totalPrice;
    private javax.swing.JTextField totalPriceTxt;
    // End of variables declaration//GEN-END:variables
   private void clearFields(){
    salesIdTxt.setText("");
    quantityTxt.setText("");
    totalPriceTxt.setText("");
    salesDateTxt.setText("");
    salesIdTxt.setEditable(true);
}

    private void loadSalesToTable() {
    dao.SalesDao dao = new dao.SalesDaoImpl();
    java.util.List<model.Sales> list = dao.displayAllSales();

    String[] cols = {"Sales ID", "Part", "Customer", "Qty", "Total Price", "Date"};
    Object[][] data = new Object[list.size()][6];

    for (int i = 0; i < list.size(); i++) {
        model.Sales s = list.get(i);
        data[i][0] = s.getSalesId();
        data[i][1] = s.getPartCode();
        data[i][2] = s.getCustomerId();
        data[i][3] = s.getQuantity();
        data[i][4] = s.getTotalPrice();
        data[i][5] = s.getSaleDate();
    }

    salesTable.setModel(new javax.swing.table.DefaultTableModel(data, cols));
}

    private void loadPartsToCombo() {
    dao.PartDao dao = new dao.PartDaoImpl();
    java.util.List<model.Part> list = dao.displayAllParts();
    partComboTxt.removeAllItems();
    for (model.Part p : list) {
        partComboTxt.addItem(p.getPartCode()); 
    }
}

private void loadCustomersToCombo() {
    dao.CustomerDao dao = new dao.CustomerDaoImpl();
    java.util.List<model.Customer> list = dao.displayAllCustomers();
    customerComboTxt.removeAllItems();
    for (model.Customer c : list) {
        customerComboTxt.addItem(c.getCustomerId()); 
    }
}

}
