/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.SupplierDao;
import dao.SupplierDaoImpl;
import javax.swing.JOptionPane;
import model.Supplier;
import util.UITheme;

/**
 * Modern Supplier Management interface with professional styling.
 * 
 * @author cyita
 */
public class SupplierManagement extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = 
        java.util.logging.Logger.getLogger(SupplierManagement.class.getName());

    /**
     * Creates new form SupplierManagement
     */
    public SupplierManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        supplierIdTxt = new javax.swing.JTextField();
        supplierFirstNameTxt = new javax.swing.JTextField();
        supplierContactInformation = new javax.swing.JTextField();
        supplierFirstName = new javax.swing.JLabel();
        supplierId = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        supplierEmail = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        contactInformation = new javax.swing.JLabel();
        supplierEmailTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        supplierTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supplier Management");
        setLocationRelativeTo(null);

        jpanel.setBackground(UITheme.BACKGROUND_LIGHT);

        jLabel2.setBackground(new java.awt.Color(204, 255, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/supplier1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jPanel1.setBackground(UITheme.SURFACE);
        jPanel1.setBorder(UITheme.createCardBorder());

        saveBtn.setBackground(UITheme.BUTTON_SECONDARY);
        saveBtn.setFont(UITheme.FONT_BUTTON);
        saveBtn.setForeground(UITheme.TEXT_WHITE);
        saveBtn.setText("Save");
        saveBtn.setBorder(UITheme.createButtonBorder(UITheme.BUTTON_SECONDARY));
        saveBtn.setFocusPainted(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(UITheme.BUTTON_DANGER);
        deleteBtn.setFont(UITheme.FONT_BUTTON);
        deleteBtn.setForeground(UITheme.TEXT_WHITE);
        deleteBtn.setText("Delete");
        deleteBtn.setBorder(UITheme.createButtonBorder(UITheme.BUTTON_DANGER));
        deleteBtn.setFocusPainted(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        supplierIdTxt.setBorder(UITheme.createInputBorder());
        supplierIdTxt.setFont(UITheme.FONT_BODY);
        supplierIdTxt.setBackground(UITheme.SURFACE);
        supplierIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierIdTxtActionPerformed(evt);
            }
        });

        supplierFirstNameTxt.setBorder(UITheme.createInputBorder());
        supplierFirstNameTxt.setFont(UITheme.FONT_BODY);
        supplierFirstNameTxt.setBackground(UITheme.SURFACE);

        supplierContactInformation.setBorder(UITheme.createInputBorder());
        supplierContactInformation.setFont(UITheme.FONT_BODY);
        supplierContactInformation.setBackground(UITheme.SURFACE);

        supplierFirstName.setFont(UITheme.FONT_BODY_BOLD);
        supplierFirstName.setForeground(UITheme.TEXT_PRIMARY);
        supplierFirstName.setText("Supplier Name");

        supplierId.setFont(UITheme.FONT_BODY_BOLD);
        supplierId.setForeground(UITheme.TEXT_PRIMARY);
        supplierId.setText("Supplier ID");

        address.setFont(UITheme.FONT_BODY_BOLD);
        address.setForeground(UITheme.TEXT_PRIMARY);
        address.setText("Address");

        supplierEmail.setFont(UITheme.FONT_BODY_BOLD);
        supplierEmail.setForeground(UITheme.TEXT_PRIMARY);
        supplierEmail.setText("Supplier Email");

        searchBtn.setBackground(UITheme.BUTTON_INFO);
        searchBtn.setFont(UITheme.FONT_BUTTON);
        searchBtn.setForeground(UITheme.TEXT_WHITE);
        searchBtn.setText("Search By ID");
        searchBtn.setBorder(UITheme.createButtonBorder(UITheme.BUTTON_INFO));
        searchBtn.setFocusPainted(false);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(UITheme.FONT_SUBHEADING);
        jLabel1.setForeground(UITheme.TEXT_PRIMARY);
        jLabel1.setText("Supplier Information");

        contactInformation.setFont(UITheme.FONT_BODY_BOLD);
        contactInformation.setForeground(UITheme.TEXT_PRIMARY);
        contactInformation.setText("Contact Information");

        supplierEmailTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(208, 208, 208), 3, true));

        addressTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(208, 208, 208), 3, true));

        updateBtn.setForeground(new java.awt.Color(241, 19, 6));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplierId)
                            .addComponent(supplierFirstName)
                            .addComponent(supplierIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplierFirstNameTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(contactInformation)
                            .addComponent(supplierContactInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplierEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(supplierEmail)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(address)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(supplierId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplierIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplierFirstName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplierFirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplierContactInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplierEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplierEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(address)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        displayBtn.setBackground(UITheme.BUTTON_PRIMARY);
        displayBtn.setFont(UITheme.FONT_BUTTON);
        displayBtn.setForeground(UITheme.TEXT_WHITE);
        displayBtn.setText("Display All");
        displayBtn.setBorder(UITheme.createButtonBorder(UITheme.BUTTON_PRIMARY));
        displayBtn.setFocusPainted(false);
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 51));

        supplierTable.setBackground(new java.awt.Color(204, 255, 102));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "supplier ID", "supplier names", "Contact", "Email", "Adress"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setFont(UITheme.FONT_BODY);
        jTable1.setGridColor(UITheme.BORDER_LIGHT);
        jTable1.setRowHeight(35);
        jTable1.setSelectionBackground(UITheme.PRIMARY_LIGHT);
        jTable1.setSelectionForeground(UITheme.TEXT_PRIMARY);
        jTable1.setBackground(UITheme.SURFACE);
        jTable1.setForeground(UITheme.TEXT_PRIMARY);
        jTable1.setShowGrid(true);
        jTable1.setShowVerticalLines(false);
        supplierTable.setViewportView(jTable1);

        jScrollPane1.setViewportView(supplierTable);

        jLabel3.setFont(UITheme.FONT_SUBHEADING);
        jLabel3.setForeground(UITheme.TEXT_PRIMARY);
        jLabel3.setText("Supplier List");

        jButton1.setBackground(UITheme.BUTTON_PRIMARY);
        jButton1.setFont(UITheme.FONT_BUTTON);
        jButton1.setForeground(UITheme.TEXT_WHITE);
        jButton1.setText("Home");
        jButton1.setBorder(UITheme.createButtonBorder(UITheme.BUTTON_PRIMARY));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelLayout = new javax.swing.GroupLayout(jpanel);
        jpanel.setLayout(jpanelLayout);
        jpanelLayout.setHorizontalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLayout.createSequentialGroup()
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1251, Short.MAX_VALUE))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addComponent(displayBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpanelLayout.setVerticalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLayout.createSequentialGroup()
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(3, 3, 3)
                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        getContentPane().add(jpanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        loadSuppliersToTable();
    }//GEN-LAST:event_displayBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if (supplierIdTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Search before updating!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (supplierIdTxt.isEditable()) {
            JOptionPane.showMessageDialog(this, "Search first. ID must be locked.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Supplier s = new Supplier();
        s.setSupplierId(supplierIdTxt.getText().trim());
        s.setSupplierNames(supplierFirstNameTxt.getText().trim());
        s.setSuppliercontact(supplierContactInformation.getText().trim());
        s.setSupplierEmail(supplierEmail.getText().trim());
        s.setAddress(addressTxt.getText().trim());

        SupplierDao dao = new SupplierDaoImpl();

        if (dao.update(s) > 0) {
            JOptionPane.showMessageDialog(this, "Supplier updated successfully!");
            supplierIdTxt.setEditable(true);
            clearFields();
            loadSuppliersToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Update failed!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String id = supplierIdTxt.getText().trim();

        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Supplier ID to search!", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        SupplierDao dao = new SupplierDaoImpl();
        Supplier s = dao.searchByCode(id);

        if (s == null) {
            JOptionPane.showMessageDialog(this, "Supplier not found!", "Not Found", JOptionPane.INFORMATION_MESSAGE);
            clearFields();
            supplierIdTxt.setEditable(true);
            return;
        }

        supplierIdTxt.setText(s.getSupplierId());
        supplierFirstNameTxt.setText(s.getSupplierNames());
        supplierContactInformation.setText(s.getSuppliercontact());
        supplierEmailTxt.setText(s.getSupplierEmail());

        addressTxt.setText(s.getAddress());

        supplierIdTxt.setEditable(false);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void supplierIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierIdTxtActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        if (supplierIdTxt.getText().trim().isEmpty() || supplierIdTxt.isEditable()) {
            JOptionPane.showMessageDialog(this, "Search first before deleting!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this supplier?",
            "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;

        SupplierDao dao = new SupplierDaoImpl();

        if (dao.delete(supplierIdTxt.getText().trim()) > 0) {
            JOptionPane.showMessageDialog(this, "Supplier deleted!");
            supplierIdTxt.setEditable(true);
            clearFields();
            loadSuppliersToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Delete failed!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        if (supplierIdTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Supplier ID is required!", "Validation", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (supplierFirstNameTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "supplier name is required!", "Validation", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!supplierFirstNameTxt.getText().trim().matches("^[A-Za-z ]+$")) {
    JOptionPane.showMessageDialog(this, "Name must contain only letters and spaces!", "VALIDATION",
        JOptionPane.ERROR_MESSAGE
    );
    return;
}
       
        if (supplierContactInformation.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Phone is required!", "Validation", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!supplierContactInformation.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Phone must contain only positive numbers!", "VALIDATION", JOptionPane.ERROR_MESSAGE);
    return;
    }
        if (supplierEmailTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email is required!", "Validation", JOptionPane.ERROR_MESSAGE);
            return;
        }
          if(supplierEmailTxt.getText().trim().isEmpty() || !supplierEmailTxt.getText().matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")){
         JOptionPane.showMessageDialog(this, "Valid Email is required!", "VALIDATION", JOptionPane.ERROR_MESSAGE);
        return;
    }

        if (addressTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Address is required!", "Validation", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Supplier s = new Supplier();
        s.setSupplierId(supplierIdTxt.getText().trim());
        s.setSupplierNames(supplierFirstName.getText().trim());
        s.setSuppliercontact(supplierContactInformation.getText().trim());
        s.setSupplierEmail(supplierEmailTxt.getText().trim());
        s.setAddress(addressTxt.getText().trim());

        SupplierDao dao = new SupplierDaoImpl();

        if (dao.create(s) > 0) {
            JOptionPane.showMessageDialog(this, "Supplier saved successfully!");
            clearFields();

        } else {
            JOptionPane.showMessageDialog(this, "Failed to save supplier!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SupplierManagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JLabel contactInformation;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpanel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField supplierContactInformation;
    private javax.swing.JLabel supplierEmail;
    private javax.swing.JTextField supplierEmailTxt;
    private javax.swing.JLabel supplierFirstName;
    private javax.swing.JTextField supplierFirstNameTxt;
    private javax.swing.JLabel supplierId;
    private javax.swing.JTextField supplierIdTxt;
    private javax.swing.JScrollPane supplierTable;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
    private void clearFields() {
    supplierIdTxt.setText("");
    supplierFirstNameTxt.setText("");
   
    supplierContactInformation.setText("");
    supplierEmailTxt.setText("");
    addressTxt.setText("");
    supplierIdTxt.setEditable(true);
}

private void loadSuppliersToTable() {
    SupplierDao dao = new SupplierDaoImpl();
    java.util.List<Supplier> list = dao.displayAllSuppliers();

    String[] cols = {"ID", "First Name", "phone", "Email", "Address"};
    Object[][] data = new Object[list.size()][5];

    for (int i = 0; i < list.size(); i++) {
        Supplier s = list.get(i);
        data[i][0] = s.getSupplierId();
        data[i][1] = s.getSupplierNames();
         data[i][2] = s.getSuppliercontact();
        data[i][3] = s.getSupplierEmail();
        data[i][4] = s.getAddress();
    }

    jTable1.setModel(new javax.swing.table.DefaultTableModel(data, cols));
}

}
